### ISSUE TITLE
Lower kama requirements for features

### ISSUE THREAD

**Issue by easafe** [typestruck/merochat#270]
Some features requirements are too high. Lower the amount of karma necessary

**Comment by Juggo0** [comment]
I suggest switching karma requirements for `Send links` and `Send images`, since links can be more dangerous than images. 
Also slashing requirements for `Send links`, `Send images` and `More tags` by 50%.

This means the following updates to [/src/Server/sql/index.sql](https://github.com/typestruck/merochat/blob/master/src/Server/sql/index.sql)

```
    (300, 'More tags', 'Increased number of max profile tags', 250),
    (400, 'Send links', 'Send and automatically highlight links in chats', 5000),
    (500, 'Send images', 'Send pictures in chats', 1500);
```

**Comment by easafe** [comment]
Where is the pull request?

**Comment by Juggo0** [comment]
`Send and automatically highlight links in chats` implies that one cannot send links below a karma threshold. But, since that is not the case the new suggestion is:

250 `More tags`
579 `Send links` (As to follow the ratio that was in place)
1500 `Send images`
