### ISSUE TITLE
Missing startup guide

### ISSUE THREAD

**Issue by curiousgeek123** [typestruck/merochat#35]
What are the steps i need to follow to run the project demo locally after cloning the repo?
and the demo url is also not working .

**Comment by easafe** [comment]
Hello @curiousgeek123 

There are instructions here https://github.com/easafe/melanchat/blob/master/CONTRIBUTING.md

However, it is nowhere as automated as I would like yet (although some easing changes will land soonish, like using addons instead of external services).

The npm file has several scripts (like `watch-s` for the server or `watch-l` for the landing page) that should be faster than recompiling the whole thing as well.

Sadly, there is not much to show yet. After I am done with the first few items of the second milestone, a very basic account creation and IM should app be up, but it will take a while to realize the full vision and scope of what the project intends be. 

Thank you for your interest! If you want to help feel free to ping me. In the meanwhile you can also check out https://wusoup.com which is a very similar idea.
